name: Asset Management Apis Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd BE
          npm cache clean --force
          npm install -g @nestjs/cli
          npm install --force
          npm run prisma:generate

  publish-gcr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Build Docker image
        run: |
          cd BE
          docker build -t ghcr.io/${{ github.repository }}/apis:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/apis:latest
